### ISSUE TITLE
Integration payment gateway

### ISSUE THREAD

**Issue by iBet7o** [numinix/fec#6]
I need to integrate a payment service that works differently.

The payment form is displayed in a modal sale and in there the whole process of payment is made.

This is the example of my provider

https://test.banwire.com/sw_ex/advanced.html

Is it possible to do an integration of this service with fec?

**Comment by scottfellnuminix** [comment]
Yes, it could be programmed to post to the confirmation page and then the
one page checkout will submit the order.  It's just a matter of having a
programmer spend the time to build the payment module.

On Tue, Apr 14, 2015 at 6:15 PM, Roberto Ramírez <notifications@github.com>
wrote:

> I need to integrate a payment service that works differently.
>
> The payment form is displayed in a modal sale and in there the whole
> process of payment is made.
>
> This is the example of my provider
>
> https://test.banwire.com/sw_ex/advanced.html
>
> Is it possible to do an integration of this service with fec?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/fec/issues/6>.
>



-- 

 *Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
 [image: Numinix] <http://www.numinix.com/>

 [image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>
